# Generated by Django 5.2 on 2025-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_drive_app', '0005_rename_evcharginglocation_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifi',
            name='authMode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wifi',
            name='channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifi',
            name='firstSeen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifi',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
