# Generated by Django 5.2 on 2025-04-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war_drive_app', '0009_wifi_channel_wifi_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifi',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='wifi',
            name='frequency',
        ),
    ]
