# Generated by Django 5.2 on 2025-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_drive_app', '0006_wifi_authmode_wifi_channel_wifi_firstseen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifi',
            name='SSID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
