# Generated by Django 5.2 on 2025-04-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war_drive_app', '0007_alter_wifi_ssid_alter_wifi_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifi',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='wifi',
            name='frequency',
        ),
    ]
