# Generated by Django 5.2 on 2025-04-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_drive_app', '0008_remove_wifi_channel_remove_wifi_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifi',
            name='channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifi',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
